### PR TITLE
Added a final exam question for the professor

### PR DESCRIPTION
**Pull request by Galiro**
I wasn’t sure if my mail client was working. I was wondering if you could provide us with some practice questions for our final?

### CODE REVIEW

**Comment by nateanl** [comment]
Hey,
I didn't receive your mail. But I will give questions like the ones in the Text.pdf. I suggest you do the questions again for the final.
Best

**Comment by Galiro** [comment]
Since the questions aren't exactly arranged by topic, are there any question numbers that should be of particular focus?

**Comment by nateanl** [comment]
Better to focus on recurrence and graph theory questions, you will need previous knoeledge to solve them, sor example, you need permutation, probability and so on,

**Comment by Galiro** [comment]
Alrighty. So looking through Text.pdf, could you provide me with some numbers to look at. They aren't exactly labeled by topic.

**Comment by nateanl** [comment]
There are a lot. Wait, ignore Q83 to Q 86,  they won't be covered in the final. Read the questions from Q1 to Q88. Q88 should be very important, I will post this on the blackboard.

**Comment by Galiro** [comment]
Hey professor! Any idea how long the test will be, how many questions?

**Pull request closed without merging**
